function diagellip(A,B)
%The function ellipse_plot is a self-contained function that takes 2x2
%matrices A and B as inputs and will plot the boundary of the ellipse generated by
%W_diag(A,B), along with the major and minor axes.
assert(isequal(size(A),size(B),[2,2]), 'The matrices are not 2x2')
L=zeros(1,4,2);
M=zeros(1,4,2);
for x=1:4
    [t,r]=cart2pol(real(A(x)),imag(A(x)));
    [p,s]=cart2pol(real(B(x)),imag(B(x)));
    L(1,x,1)=t;
    L(1,x,2)=r;
    M(1,x,1)=p;
    M(1,x,2)=s;
end
h=cos(L(1,1,1)+M(1,1,1))*L(1,1,2)*M(1,1,2)+cos(L(1,4,1)+M(1,4,1))*L(1,4,2)*M(1,4,2);
k=sin(L(1,1,1)+M(1,1,1))*L(1,1,2)*M(1,1,2)+sin(L(1,4,1)+M(1,4,1))*L(1,4,2)*M(1,4,2);
a=L(1,3,2)*M(1,2,2)+L(1,2,2)*M(1,3,2);
b=L(1,3,2)*M(1,2,2)-L(1,2,2)*M(1,3,2);
c=(L(1,2,1)+M(1,3,1)+L(1,3,1)+M(1,2,1))/2;
plot(h,k,'or', 'LineWidth',2)
%This plots the center of the ellipse
%To plot the ellipse, we will grab the points of the normal ellipse, rotate
%them, and then translate them to the proper point. To begin, we must first
%acquire the coordinates of the two vertices of the ellipse's major axis
t=linspace(0,2*pi);
X=a*cos(t);
Y=b*sin(t);
Z=zeros(1,length(X));
for j=1:length(X)
    Z(1,j)=X(1,j)+1i*Y(1,j);
end
W=Z*exp(1i*c)+h+1i*k;
plot(real(W),imag(W),'r*-', 'LineWidth',2)
x1=(-a)*exp(1i*c)+h+1i*k;
x2=(a)*exp(1i*c)+h+1i*k;
y1=(-b*1i)*exp(1i*c)+h+1i*k;
y2=(b*1i)*exp(1i*c)+h+1i*k;
plot([real(x1),real(x2)],[imag(x1),imag(x2)],'g.-','LineWidth',2)
plot([real(y1),real(y2)],[imag(y1),imag(y2)],'g.-','LineWidth',2)
axis equal

